using System.Collections.Generic;
using TMPro;
using UnityEditor.Experimental.GraphView;
using UnityEngine;

public class Orders : MonoBehaviour
{
    public CollisionTracker collisionTracker;
    public List<GameObject> Carrot = new List<GameObject>();
    public List<GameObject> Tomato = new List<GameObject>();
    public List<GameObject> Lettuce = new List<GameObject>();

    public int Money = 0;
    public int carrotPrice = 25;
    public int tomatoPrice = 25;
    public int lettucePrice = 25;

    public int requiredCarrots;
    public int requiredTomatoes;
    public int requiredLettuces;

    public TMP_Text questText;
    public int windowNumber;

    private GameObject drugged;
    public int sus = 0;
    public int addic = 0;
    public int susMax = 100;
    public int addicMax = 100;
    public int susMin = 0;
    public int addicMin = 0;
    
    void Start()
    {
        GenerateNewOrder();
    }

    void Update()
    {
        CheckOrder();
    }

    private void OnTriggerEnter(Collider other)
    {
        
        if (other.CompareTag("GrownCarrot") && !Carrot.Contains(other.gameObject))
            Carrot.Add(other.gameObject);
        else if (other.CompareTag("Tomato") && !Tomato.Contains(other.gameObject))
            Tomato.Add(other.gameObject);
        else if (other.CompareTag("Lettuce") && !Lettuce.Contains(other.gameObject))
            Lettuce.Add(other.gameObject);
        UpdateQuestText();
    }

    void GenerateNewOrder()
    {
        requiredCarrots = Random.Range(1, 3);
        requiredTomatoes = Random.Range(4, 8);
        requiredLettuces = Random.Range(1, 2);

        if (requiredCarrots + requiredTomatoes + requiredLettuces == 0)
            GenerateNewOrder();

        Debug.Log($"New Order: {requiredCarrots} Carrots, {requiredTomatoes} Tomatoes, {requiredLettuces} Lettuces");

        UpdateQuestText();
    }

    void UpdateQuestText()
    {
        questText.text =
            $"<b>Customer {windowNumber}</b>\n" +
            $"<b>Current Order:</b>\n" +
            $"Carrots: {Carrot.Count}/{requiredCarrots}\n" +
            $"Tomatoes: {Tomato.Count}/{requiredTomatoes}\n" +
            $"Lettuce: {Lettuce.Count}/{requiredLettuces}";
            
    }

    void CheckOrder()
    {
        if (Carrot.Count >= requiredCarrots &&
            Tomato.Count >= requiredTomatoes &&
            Lettuce.Count >= requiredLettuces)
        {
            Sold();
            GenerateNewOrder();
            UpdateQuestText();
        }
    }
    void EvaluateDrugs(List<GameObject> crops)
    {
        foreach (var crop in crops)
        {
            if (crop == null) continue;

            Drugged drug = crop.GetComponent<Drugged>();

            if (drug == null)
            {
                sus -= 10;
                addic -= 5;
            }
            else if (drug.drug1)
            {
                sus += 10;
                addic += 10;
            }
            else if (drug.drug2)
            {
                sus += 20;
                addic += 25;
            }
            else if (drug.drug3)
            {
                sus += 50;
                addic += 40;
            }
        }
    }

    public void Sold()
    {
        Money += carrotPrice * Carrot.Count + tomatoPrice * Tomato.Count + lettucePrice * Lettuce.Count;

        EvaluateDrugs(Carrot);
        EvaluateDrugs(Tomato);
        EvaluateDrugs(Lettuce);


        foreach (var l in Lettuce) Destroy(l);
        foreach (var t in Tomato) Destroy(t);
        foreach (var c in Carrot) Destroy(c);

        Lettuce.Clear();
        Tomato.Clear();
        Carrot.Clear();
        collisionTracker.collidingObjects.Clear();


        Debug.Log("Money: " + Money);
        Debug.Log("Suspicion: " + sus);
        Debug.Log("Addictivness: " + addic);
        WinCon();
    }


    public void WinCon()
    {
        if (sus > susMax)
        {
            Debug.Log("U lost");
        }
        else if(addic > addicMax)
        {
            Debug.Log("U won");
        }
    }
}